import "./globals.css";

import { Nunito_Sans } from "next/font/google";

const nunito = Nunito_Sans({
  weight: ["600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
